#!/bin/bash

grade=59
if [ $grade -ge 90 ] && [ $grade -le 100 ]
then
    echo "Excellent!"

elif [ $grade -ge 80 ]
then
    echo "Good"

elif [ $grade -lt 80 ] && [ $grade -ge 60 ]
then
    echo "OK, but try harder!"

else 
    echo "Do better next time"
fi


#!/bin/bash

age=14
grade=79

if [ $age -gt 18 ]; then
    echo "You are eligible based on age"
    if [ $grade -gt 80 ]; then 
        echo "You are eligible based on grade"
        echo "Congratulations! You are eligible"
    else
        echo "Sorry your grade is not high enough"
    fi
else
    echo "Sorry you are not eligible"
fi

#!/bin/bash

for faad in $(seq 1 5)
do
    echo "faad: $faad"
done

for (( i=1; i<=5; i++))
do
    if [ $i -eq 3 ]
    then 
        continue
    fi
    echo "Number: $i"
done

#!/bin/bash

hello_world() {
    echo "Hello World!"
}

greet_person() {
    local name="$1"
    echo "Hello, $name!"

}

greet_person "Ahmed"
greet_person "Gandu"

print_args() {
    echo "Number of arguments: $#"
    echo "Script name: $0"
    echo "First argument: $1"
    echo "Second argument: $2"
    echo "All arguments: $@"

}

print_args "Bodrul Ken" "Gandu"

#!/bin/bash

# greet_user(){
#    echo "What is your name?"
#    read name
#    echo "Hello, $name!"
#}


# greet_user

greet(){
    local name
    if [ $# -eq 0 ]; then
        echo "What is your name?"
        read name
    else
        name="$1"
    fi
    echo "Hello, $name!"

}
greet "Hasnat"


#!/bin/bash

validate_age() {
    local age=$1

    if [[ ! $age =~ ^[0-9]+$ ]]; then
        echo "Invalid age. Please provide a numeric value."
        return 1
    fi
# Checks the user has entered appropriate data
    if (( age < 18 )); then
        echo "Sorry, you must be at least 18 years old."
        return 1
    fi

    echo "Congratulations! You are eligible."
    return 0
}

echo "Please enter your age"
read user_age
validate_age "$user_age"
exit_code=$?

if (( exit_code != 0 )); then
    echo "Input validation failed."

else
    echo "Validation passed!"
fi

#!/bin/bash

get_file_count(){
    local directory="$1"
    local file_count

    file_count=$(ls "$directory" | wc -l)

    echo "Number of files in $directory: $file_count"
}

get_file_count "/home/hasnat"


#!/bin/bash

num1=10
num2=0

if [ $num2 -eq 0 ]; then
    echo "Division by zero is not allowed"
    exit 1
fi

result=$((num1 / num2))

echo "The result is: $result"
