#!/bin/bash

age=14
grade=79

if [ $age -gt 18 ]; then
    echo "You are eligible based on age"
    if [ $grade -gt 80 ]; then 
        echo "You are eligible based on grade"
        echo "Congratulations! You are eligible"
    else
        echo "Sorry your grade is not high enough"
    fi
else
    echo "Sorry you are not eligible"
fi
