#!/bin/bash

set -e

echo "Before the script"

nonexistentcommand

echo "After the script"



#!/bin/bash

set -u

# echo "The value of variable X: $X"

X=10
Y=20
Z=$((X + Y + W))
echo "Z equals: $Z"

#!/bin/bash


set -x

echo "Starting the script"
X=10
Y=20
Z=$((X + Y))
echo "The values of Z is: $Z"
